[package]
authors = ["Dirk Kretschmann <kretschmanndi@gmail.com>"]
edition = "2018"
license = "MIT"
name = "twilight-commander"
version = "0.11.2"

[dependencies]
serde = { version = "1.0.101",  features = ["derive"] }
signal-hook = "0.1.10"
termion = "1.5.3"
toml = "0.5.3"
