#!/bin/bash

if [[ -d $1 ]]; then
    DIRNAME="$(readlink -f $1)"
elif [[ -f $1 ]]; then
    echo "'$1' is a file, please pass a directory"
    exit 1
else
    echo "tcide: opens a tmux session with vim and integrated twilight-commander"
    echo "usage: tcide <directory>"
    exit 1
fi

echo "opening $DIRNAME"

# TODO: check for used vim servers with 'vim --serverlist'?
# tmux does not allow reuse of session names, so ths seems unecessary

tmux new-session \
    -s $DIRNAME \
    -d twilight-commander \
        --behavior.file_action="vim --servername $DIRNAME --remote-tab %s" \
        --setup.working_dir="$DIRNAME" \
        --debug.enabled=true \
    \; \
    split-window -h "vim --servername $DIRNAME" \; \
    split-window -v \; \
    resize-pane -L 40 \; \
    resize-pane -D 10 \; \
    attach
