#!/bin/bash

# Opens a tmux session with 3 panes: vim, twilight-commander, terminal.
# Hitting the file_action key (default: return) on a file entry opens it in a new vim tab.
# You need to compile vim with the clientserver option:
# git clone https://github.com/vim/vim.git
# cd vim/src
# make distclean
# ./configure +clientserver
# make
# sudo make install


if [[ -d $1 ]]; then
    DIRNAME="$(readlink -f "$1")"
    BASENAME="$(basename "$DIRNAME")"
elif [[ -f $1 ]]; then
    echo "'$1' is a file, please pass a directory"
    exit 1
else
    echo "tcide: opens a tmux session with vim and integrated twilight-commander"
    echo "usage: tcide <directory>"
    exit 1
fi

echo "opening $DIRNAME"

# TODO: check for used vim servers with 'vim --serverlist'?
# tmux does not allow reuse of session names, so ths seems unecessary

tmux new-session \
    -s "$DIRNAME" \
    -d twilight-commander \
        --behavior.file_action="vim --servername $DIRNAME --remote-tab %s" \
        --setup.working_dir="$DIRNAME" \
    \; \
    split-window -h "vim --servername $DIRNAME" \; \
    split-window -v \; \
    resize-pane -L 40 \; \
    resize-pane -D 10 \; \
    set-option set-titles on \; \
    set-option set-titles-string "$BASENAME" \; \
    attach

